### ISSUE TITLE
Project not uploading / Aw snap! on chrome...

### ISSUE THREAD

**Issue by ktsimouris** [AR-js-org/studio#101] opened 2020-09-30 06:52 UTC
Hello everyone, 

I've been using the studio for a little while now, and no issues had fallen to my attention.
Today, trying to upload a new marker-based project, I upload my marker, then the 3D model (gltf and bin as I should in a zip file) and when I click "post on github" I get an "Aw! Snap." reaction from chrome with the error code "Error code: STATUS_BREAKPOINT".

My model is not damaged, it works just fine, it just is the largest file i've ever used in the studio. It is 30MB (while the limit is at 50MB). I am attaching my files here for reference, along with the screenshot of the error code.

I hope this is fixable...
![Screenshot_5](https://user-images.githubusercontent.com/64761473/94652219-53761e80-0302-11eb-81f8-06c1bb4401a7.png)

P.S.: I cannot upload the zip file here, because it is too large. But if someone wants to try it out, message me and I'll send you the files I am using!

**Comment by ktsimouris** [comment] 2020-09-30 09:33
:UPDATE:

It looks like the generated package for the project is about 122MB in total. I downloaded it before clicking "Publish on GitHub" and saw that.
Could that be the issue?

I tried to make the repository from scratch with the generated code and assets, but GitHub does not let me upload anything larger than 25MB.

**Comment by nicolocarpignoli** [comment] 2020-10-02 09:51
@ktsimouris try to upload using the git command line tool or other software for git (like Sourcetree, GitKraken, etc.).
Maybe is the Github Web that is limiting the file size.

If the problem persist, please open the issue again. 
I will close this as the problem is out of the scope of AR.js Studio (we are stating the 25mb limit for the GLTF) :)

**Closed by nicolocarpignoli** 2020-10-02 09:51 UTC
